// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by scripts/generate-binding.mjs */

import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)

const TARGETS = [
  {
    platform: 'darwin',
    arch: 'arm64',
    abi: null,
    packageName: '@aleburato/primeval-darwin-arm64',
    localFile: './primeval-node.darwin-arm64.node'
  },
  {
    platform: 'darwin',
    arch: 'x64',
    abi: null,
    packageName: '@aleburato/primeval-darwin-x64',
    localFile: './primeval-node.darwin-x64.node'
  },
  {
    platform: 'linux',
    arch: 'arm64',
    abi: 'gnu',
    packageName: '@aleburato/primeval-linux-arm64-gnu',
    localFile: './primeval-node.linux-arm64-gnu.node'
  },
  {
    platform: 'linux',
    arch: 'x64',
    abi: 'gnu',
    packageName: '@aleburato/primeval-linux-x64-gnu',
    localFile: './primeval-node.linux-x64-gnu.node'
  },
  {
    platform: 'win32',
    arch: 'x64',
    abi: 'msvc',
    packageName: '@aleburato/primeval-win32-x64-msvc',
    localFile: './primeval-node.win32-x64-msvc.node'
  }
]

// Match the current platform/arch against declared targets.
// Add musl detection here if musl targets are ever shipped.
function findTarget() {
  return TARGETS.find(
    (t) => t.platform === process.platform && t.arch === process.arch,
  ) ?? null
}

function requireLocalFile(localFile) {
  switch (localFile) {
    case './primeval-node.darwin-arm64.node':
      return require('./primeval-node.darwin-arm64.node')
    case './primeval-node.darwin-x64.node':
      return require('./primeval-node.darwin-x64.node')
    case './primeval-node.linux-arm64-gnu.node':
      return require('./primeval-node.linux-arm64-gnu.node')
    case './primeval-node.linux-x64-gnu.node':
      return require('./primeval-node.linux-x64-gnu.node')
    case './primeval-node.win32-x64-msvc.node':
      return require('./primeval-node.win32-x64-msvc.node')
    default:
      throw new Error(`Unsupported local binding file: ${localFile}`)
  }
}

function requireOptionalPackage(packageName) {
  switch (packageName) {
    case '@aleburato/primeval-darwin-arm64':
      return require('@aleburato/primeval-darwin-arm64')
    case '@aleburato/primeval-darwin-x64':
      return require('@aleburato/primeval-darwin-x64')
    case '@aleburato/primeval-linux-arm64-gnu':
      return require('@aleburato/primeval-linux-arm64-gnu')
    case '@aleburato/primeval-linux-x64-gnu':
      return require('@aleburato/primeval-linux-x64-gnu')
    case '@aleburato/primeval-win32-x64-msvc':
      return require('@aleburato/primeval-win32-x64-msvc')
    default:
      throw new Error(`Unsupported native package: ${packageName}`)
  }
}

function loadNativeBinding() {
  const target = findTarget()
  if (!target) {
    throw new Error(
      `Unsupported OS: ${process.platform}, architecture: ${process.arch}. This package ships prebuilds only for the targets declared in package.json napi.targets.`,
    )
  }

  let firstError
  try {
    return requireLocalFile(target.localFile)
  } catch (error) {
    firstError = error
  }

  try {
    return requireOptionalPackage(target.packageName)
  } catch (error) {
    const combined = new Error(
      `Failed to load native binding for ${target.localFile}. Tried local file and package ${target.packageName}.`,
    )
    combined.cause = firstError
    throw combined
  }
}

export const { cancelApproximate, startApproximate } = loadNativeBinding()
