import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  readPackageMetadata,
  requiredString,
  runtimeTargetForTarget,
  validatePackageMetadata,
} from "./napi-targets.mjs";

const SCRIPTS_DIR = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_PACKAGE_JSON = path.resolve(SCRIPTS_DIR, "..", "package.json");
const DEFAULT_OUTPUT = path.resolve(SCRIPTS_DIR, "..", "binding.js");

export function bindingMetadataForPackage(pkg) {
  const { packageName, targets } = validatePackageMetadata(pkg);
  const binaryName = requiredString(pkg.napi?.binaryName, "package.json napi.binaryName");

  return {
    targets: targets.map((target) => {
      const runtime = runtimeTargetForTarget(target);
      return {
        ...runtime,
        packageName: `${packageName}-${runtime.suffix}`,
        localFile: `./${binaryName}.${runtime.suffix}.node`,
      };
    }),
  };
}

function renderTargetMetadata(targets) {
  return targets
    .map(
      (target) => `  {
    platform: '${target.platform}',
    arch: '${target.arch}',
    abi: ${target.abi === null ? "null" : `'${target.abi}'`},
    packageName: '${target.packageName}',
    localFile: '${target.localFile}'
  }`,
    )
    .join(",\n");
}

function renderSwitchCases(targets, key) {
  return targets
    .map(
      (target) => `    case '${target[key]}':
      return require('${target[key]}')`,
    )
    .join("\n");
}

export function renderBindingLoader(pkg) {
  const { targets } = bindingMetadataForPackage(pkg);

  return `// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by scripts/generate-binding.mjs */

import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)

const TARGETS = [
${renderTargetMetadata(targets)}
]

// Match the current platform/arch against declared targets.
// Add musl detection here if musl targets are ever shipped.
function findTarget() {
  return TARGETS.find(
    (t) => t.platform === process.platform && t.arch === process.arch,
  ) ?? null
}

function requireLocalFile(localFile) {
  switch (localFile) {
${renderSwitchCases(targets, "localFile")}
    default:
      throw new Error(\`Unsupported local binding file: \${localFile}\`)
  }
}

function requireOptionalPackage(packageName) {
  switch (packageName) {
${renderSwitchCases(targets, "packageName")}
    default:
      throw new Error(\`Unsupported native package: \${packageName}\`)
  }
}

function loadNativeBinding() {
  const target = findTarget()
  if (!target) {
    throw new Error(
      \`Unsupported OS: \${process.platform}, architecture: \${process.arch}. This package ships prebuilds only for the targets declared in package.json napi.targets.\`,
    )
  }

  let firstError
  try {
    return requireLocalFile(target.localFile)
  } catch (error) {
    firstError = error
  }

  try {
    return requireOptionalPackage(target.packageName)
  } catch (error) {
    const combined = new Error(
      \`Failed to load native binding for \${target.localFile}. Tried local file and package \${target.packageName}.\`,
    )
    combined.cause = firstError
    throw combined
  }
}

export const { cancelApproximate, startApproximate } = loadNativeBinding()
`;
}

export function writeBindingLoader(
  packageJsonPath = DEFAULT_PACKAGE_JSON,
  outputPath = DEFAULT_OUTPUT,
) {
  const pkg = readPackageMetadata(packageJsonPath);
  const source = renderBindingLoader(pkg);
  fs.writeFileSync(outputPath, source);
  return outputPath;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const packageJsonPath = process.argv[2]
    ? path.resolve(process.argv[2])
    : DEFAULT_PACKAGE_JSON;
  const outputPath = process.argv[3] ? path.resolve(process.argv[3]) : DEFAULT_OUTPUT;
  writeBindingLoader(packageJsonPath, outputPath);
  console.log(path.relative(process.cwd(), outputPath));
}
