import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  readPackageMetadata,
  runtimeTargetForTarget,
  validatePackageMetadata,
} from "./napi-targets.mjs";

const SCRIPTS_DIR = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_PACKAGE_JSON = path.resolve(SCRIPTS_DIR, "..", "package.json");
const DEFAULT_OUTPUT = path.resolve(SCRIPTS_DIR, "..", "binding.js");

function requiredString(value, label) {
  if (typeof value !== "string" || value.length === 0) {
    throw new Error(`${label} is required`);
  }
  return value;
}

export function bindingMetadataForPackage(pkg) {
  const { packageName, targets } = validatePackageMetadata(pkg);
  const binaryName = requiredString(pkg.napi?.binaryName, "package.json napi.binaryName");

  return {
    targets: targets.map((target) => {
      const runtime = runtimeTargetForTarget(target);
      return {
        ...runtime,
        packageName: `${packageName}-${runtime.suffix}`,
        localFile: `./${binaryName}.${runtime.suffix}.node`,
      };
    }),
  };
}

function renderTargetMetadata(targets) {
  return targets
    .map(
      (target) => `  {
    platform: '${target.platform}',
    arch: '${target.arch}',
    abi: ${target.abi === null ? "null" : `'${target.abi}'`},
    packageName: '${target.packageName}',
    localFile: '${target.localFile}'
  }`,
    )
    .join(",\n");
}

function renderSwitchCases(targets, key) {
  return targets
    .map(
      (target) => `    case '${target[key]}':
      return require('${target[key]}')`,
    )
    .join("\n");
}

export function renderBindingLoader(pkg) {
  const { targets } = bindingMetadataForPackage(pkg);

  return `// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by scripts/generate-binding.mjs */

import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)
const rootPackage = require('./package.json')
const packageVersion = rootPackage.version
let nativeBinding = null
const loadErrors = []

const TARGETS = [
${renderTargetMetadata(targets)}
]

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (file) => file.includes('libc.musl-') || file.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return require('node:fs').readFileSync('/usr/bin/ldd', 'utf8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header?.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    return report.sharedObjects.some(isFileMusl)
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('node:child_process')
      .execSync('ldd --version', { encoding: 'utf8' })
      .includes('musl')
  } catch {
    return false
  }
}

function currentRuntime() {
  if (process.platform === 'linux') {
    return {
      platform: process.platform,
      arch: process.arch,
      abi: isMusl() ? 'musl' : 'gnu'
    }
  }

  if (process.platform === 'win32') {
    return {
      platform: process.platform,
      arch: process.arch,
      abi: 'msvc'
    }
  }

  return {
    platform: process.platform,
    arch: process.arch,
    abi: null
  }
}

function formatRuntime(runtime) {
  return runtime.abi
    ? \`\${runtime.platform}-\${runtime.arch}-\${runtime.abi}\`
    : \`\${runtime.platform}-\${runtime.arch}\`
}

function resolveTarget(runtime) {
  return (
    TARGETS.find(
      (target) =>
        target.platform === runtime.platform &&
        target.arch === runtime.arch &&
        target.abi === runtime.abi,
    ) ?? null
  )
}

function requireLocalFile(localFile) {
  switch (localFile) {
${renderSwitchCases(targets, "localFile")}
    default:
      throw new Error(\`Unsupported local binding file: \${localFile}\`)
  }
}

function requireOptionalPackage(packageName) {
  switch (packageName) {
${renderSwitchCases(targets, "packageName")}
    default:
      throw new Error(\`Unsupported native package: \${packageName}\`)
  }
}

function assertPackageVersion(packageName) {
  if (
    !process.env.NAPI_RS_ENFORCE_VERSION_CHECK ||
    process.env.NAPI_RS_ENFORCE_VERSION_CHECK === '0'
  ) {
    return
  }

  const installedVersion = require(\`\${packageName}/package.json\`).version
  if (installedVersion !== packageVersion) {
    throw new Error(
      \`Native binding package version mismatch, expected \${packageVersion} but got \${installedVersion}. You can reinstall dependencies to fix this issue.\`,
    )
  }
}

function loadNativeBinding() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH)
    } catch (error) {
      loadErrors.push(error)
    }
  }

  const runtime = currentRuntime()
  const target = resolveTarget(runtime)
  if (!target) {
    throw new Error(
      \`Unsupported OS: \${process.platform}, architecture: \${process.arch}. This package ships prebuilds only for the targets declared in package.json napi.targets.\`,
    )
  }

  try {
    return requireLocalFile(target.localFile)
  } catch (error) {
    loadErrors.push(error)
  }

  try {
    const binding = requireOptionalPackage(target.packageName)
    assertPackageVersion(target.packageName)
    return binding
  } catch (error) {
    loadErrors.push(error)
  }

  const error = new Error(
    \`Failed to load native binding for \${formatRuntime(runtime)}. Tried local file \${target.localFile} and package \${target.packageName}.\`,
  )
  error.cause = loadErrors[0]
  throw error
}

nativeBinding = loadNativeBinding()

export const { cancelApproximate, startApproximate } = nativeBinding
`;
}

export function writeBindingLoader(
  packageJsonPath = DEFAULT_PACKAGE_JSON,
  outputPath = DEFAULT_OUTPUT,
) {
  const pkg = readPackageMetadata(packageJsonPath);
  const source = renderBindingLoader(pkg);
  fs.writeFileSync(outputPath, source);
  return outputPath;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const packageJsonPath = process.argv[2]
    ? path.resolve(process.argv[2])
    : DEFAULT_PACKAGE_JSON;
  const outputPath = process.argv[3] ? path.resolve(process.argv[3]) : DEFAULT_OUTPUT;
  writeBindingLoader(packageJsonPath, outputPath);
  console.log(path.relative(process.cwd(), outputPath));
}
